# Prometheus Configuration for NewPennine WMS Blue-Green Deployment

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # NewPennine Blue Environment
  - job_name: 'newpennine-blue'
    static_configs:
      - targets: ['newpennine-blue:3000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s
    honor_labels: true
    labels:
      environment: 'blue'
      service: 'newpennine-wms'

  # NewPennine Green Environment
  - job_name: 'newpennine-green'
    static_configs:
      - targets: ['newpennine-green:3000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s
    honor_labels: true
    labels:
      environment: 'green'
      service: 'newpennine-wms'

  # Nginx Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 15s
    labels:
      service: 'nginx-lb'

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    labels:
      service: 'redis-cache'

  # Docker Container Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    labels:
      service: 'docker-metrics'

  # Node Exporter (System Metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    labels:
      service: 'system-metrics'

  # Health Check Service
  - job_name: 'health-checker'
    static_configs:
      - targets: ['health-checker:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    labels:
      service: 'health-checker'

# Remote write configuration for long-term storage
remote_write:
  - url: "http://prometheus-remote-storage:9201/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Recording rules for performance optimization
recording_rules:
  - name: newpennine.rules
    rules:
      - record: newpennine:request_rate
        expr: rate(http_requests_total[5m])
      
      - record: newpennine:error_rate
        expr: rate(http_requests_total{status=~"5.."}[5m])
      
      - record: newpennine:response_time_95th
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))
      
      - record: newpennine:cpu_usage
        expr: rate(process_cpu_seconds_total[5m])
      
      - record: newpennine:memory_usage
        expr: process_resident_memory_bytes
      
      - record: newpennine:active_connections
        expr: nginx_connections_active