openapi: 3.1.0
info:
  title: Online Stock Control System API
  version: 2.1.0
  description: |
    Consolidated API specification for the Online Stock Control System
    
    ## API Consolidation Changes
    - Merged v1 and v2 endpoints into a unified structure
    - Improved authentication and authorization
    - Added comprehensive monitoring and metrics endpoints
  
  contact:
    name: Pennine WMS Development Team
    email: dev-support@pennine-wms.com
  
  x-api-migration:
    deprecated-versions:
      - v1
      - v2
    migration-guide: https://pennine-wms.com/docs/api-migration

servers:
  - url: https://api.pennine-wms.com/api
    description: Production API Server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    
  schemas:
    HealthStatus:
      type: object
      properties:
        status:
          type: string
          enum: ['healthy', 'degraded', 'unhealthy']
        timestamp:
          type: string
          format: date-time
        services:
          type: object
          additionalProperties:
            type: string
            enum: ['operational', 'minor_issues', 'major_outage']
    
    MetricsResponse:
      type: object
      properties:
        system_load:
          type: number
          format: float
        memory_usage:
          type: number
          format: float
        cpu_usage:
          type: number
          format: float
        database_connections:
          type: integer
    
    AlertConfig:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
        severity:
          type: string
          enum: ['low', 'medium', 'high', 'critical']
        status:
          type: string
          enum: ['active', 'disabled', 'paused']

paths:
  /health:
    get:
      summary: System Health Check
      description: Provides an overview of the system's current health status
      operationId: getSystemHealth
      responses:
        '200':
          description: Successful health check
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '503':
          description: Service Unavailable
  
  /monitoring/performance:
    get:
      summary: System Performance Metrics
      description: Retrieve current system performance metrics
      operationId: getPerformanceMetrics
      responses:
        '200':
          description: Performance metrics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse'
  
  /alerts/config:
    get:
      summary: List Alert Configurations
      description: Retrieve all configured alerts
      operationId: listAlertConfigs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved alert configurations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AlertConfig'
        '401':
          description: Unauthorized - Authentication required
  
  /cache/metrics:
    get:
      summary: Cache Performance Metrics
      description: Retrieve metrics about the system's cache performance
      operationId: getCacheMetrics
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Cache metrics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  hit_rate:
                    type: number
                    format: float
                  miss_rate:
                    type: number
                    format: float
                  total_requests:
                    type: integer
        '401':
          description: Unauthorized - Authentication required

x-deprecated-endpoints:
  - /api/v1/*
  - /api/v2/*

x-migration-notes: |
  ## Migration Guide
  
  ### Authentication
  - All protected endpoints now require JWT authentication
  - Use the `bearerAuth` security scheme with a valid JWT token
  
  ### Endpoint Changes
  - `/api/v1/health` -> `/api/health`
  - `/api/v1/monitoring/*` -> `/api/monitoring/*`
  - `/api/v1/alerts/*` -> `/api/alerts/*`
  - `/api/v1/metrics/*` -> `/api/metrics/*`
  - `/api/v1/cache/*` -> `/api/cache/*`
  
  ### Authentication Requirements
  - Public Endpoints: 
    - `/health`
    - `/monitoring/*`
    - `/metrics/*`
  - Protected Endpoints (require JWT):
    - `/alerts/*`
    - `/cache/*`
  
  ### Example Migration
  ```typescript
  // Old (v1)
  fetch('/api/v1/alerts/config')
  
  // New (v2.1)
  fetch('/api/alerts/config', {
    headers: {
      'Authorization': `Bearer ${yourJwtToken}`
    }
  })
  ```